spring:
  application:
    name: gs-gateway           

server:
  port: 8080


hystrix.command.mycmd.circuitBreaker.requestVolumeThreshold: 5
hystrix.command.mycmd.circuitBreaker.errorThresholdPercentage: 50
hystrix.command.mycmd.metrics.rollingStats.timeInMilliseconds: 10000
hystrix.command.mycmd.circuitBreaker.sleepWindowInMilliseconds: 30000

              
gs-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8888 