spring:
  application:
    name: gs-gateway

server:
  port: 8080

gs-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8888,localhost:9092
ServerListRefreshInterval: 5000
